packages:
  - "packages/**"
  - "extension"
minimumReleaseAge: 10080
catalog:
  vitest: 4.0.16
  typescript: 5.9.3
  webextension-polyfill: 0.12.0
  "@types/webextension-polyfill": 0.12.3
  "eventemitter3": 5.0.1
  ox: 0.9.14
