packages:
  - "packages/**"
  - "extension"
  - "app"
minimumReleaseAge: 10080
catalog:
  vitest: 3.2.4
  typescript: 5.9.2
  webextension-polyfill: 0.12.0
  "@types/webextension-polyfill": 0.12.3
  "eventemitter3": 5.0.1
