packages:
  - packages/**
  - extension

allowBuilds:
  esbuild: true
  spawn-sync: true

catalog:
  '@types/webextension-polyfill': 0.12.3
  eventemitter3: 5.0.1
  ox: 0.9.14
  typescript: 6.0.3
  vitest: 4.1.9
  webextension-polyfill: 0.12.0

minimumReleaseAge: 10080
