import type {
  ApplyTransactionDraftEditInput,
  ConfirmNewMnemonicInput,
  CreateWalletFromMnemonicInput,
  DeriveAccountInput,
  ExportMnemonicInput,
  ExportPrivateKeyInput,
  GenerateMnemonicInput,
  HideHdAccountInput,
  ImportMnemonicInput,
  ImportPrivateKeyInput,
  ImportWalletFromMnemonicInput,
  ImportWalletFromPrivateKeyInput,
  LockSessionInput,
  MarkBackedUpInput,
  RemovePrivateKeyKeyringInput,
  RenameAccountInput,
  RenameKeyringInput,
  RequestSendTransactionApprovalInput,
  RerunTransactionPrepareInput,
  ResolveApprovalInput,
  SelectWalletChainInput,
  SetAutoLockDurationInput,
  SwitchActiveAccountInput,
  TrustedWalletApi,
  UnhideHdAccountInput,
  UnlockSessionInput,
  WalletApiAccountsByKeyringInput,
  WalletApiApprovalDetailInput,
  WalletApiNativeBalanceInput,
  WalletApiTransactionDetailInput,
  WalletApiTransactionsInput,
} from "./api.js";

export type TrustedWalletApiCall = <TResult>(path: string, input?: unknown) => Promise<TResult>;

export const createTrustedWalletApiFromCall = (call: TrustedWalletApiCall): TrustedWalletApi => ({
  session: {
    getStatus: () => call("session.getStatus"),
    unlock: (input: UnlockSessionInput) => call("session.unlock", input),
    lock: (input?: LockSessionInput) => call("session.lock", input),
    resetAutoLockTimer: () => call("session.resetAutoLockTimer"),
    setAutoLockDuration: (input: SetAutoLockDurationInput) => call("session.setAutoLockDuration", input),
  },
  setup: {
    getStatus: () => call("setup.getStatus"),
    generateMnemonic: (input?: GenerateMnemonicInput) => call("setup.generateMnemonic", input),
    createWalletFromMnemonic: (input: CreateWalletFromMnemonicInput) => call("setup.createWalletFromMnemonic", input),
    importWalletFromMnemonic: (input: ImportWalletFromMnemonicInput) => call("setup.importWalletFromMnemonic", input),
    importWalletFromPrivateKey: (input: ImportWalletFromPrivateKeyInput) =>
      call("setup.importWalletFromPrivateKey", input),
  },
  accounts: {
    listCurrentChain: () => call("accounts.listCurrentChain"),
    switchActive: (input: SwitchActiveAccountInput) => call("accounts.switchActive", input),
  },
  networks: {
    getSelectedChain: () => call("networks.getSelectedChain"),
    list: () => call("networks.list"),
    select: (input: SelectWalletChainInput) => call("networks.select", input),
  },
  balances: {
    getNative: (input: WalletApiNativeBalanceInput) => call("balances.getNative", input),
  },
  approvals: {
    listPending: () => call("approvals.listPending"),
    getDetail: (input: WalletApiApprovalDetailInput) => call("approvals.getDetail", input),
    resolve: (input: ResolveApprovalInput) => call("approvals.resolve", input),
  },
  keyrings: {
    list: () => call("keyrings.list"),
    getAccountsByKeyring: (input: WalletApiAccountsByKeyringInput) => call("keyrings.getAccountsByKeyring", input),
    getBackupStatus: () => call("keyrings.getBackupStatus"),
    confirmNewMnemonic: (input: ConfirmNewMnemonicInput) => call("keyrings.confirmNewMnemonic", input),
    importMnemonic: (input: ImportMnemonicInput) => call("keyrings.importMnemonic", input),
    importPrivateKey: (input: ImportPrivateKeyInput) => call("keyrings.importPrivateKey", input),
    deriveAccount: (input: DeriveAccountInput) => call("keyrings.deriveAccount", input),
    renameKeyring: (input: RenameKeyringInput) => call("keyrings.renameKeyring", input),
    renameAccount: (input: RenameAccountInput) => call("keyrings.renameAccount", input),
    markBackedUp: (input: MarkBackedUpInput) => call("keyrings.markBackedUp", input),
    hideHdAccount: (input: HideHdAccountInput) => call("keyrings.hideHdAccount", input),
    unhideHdAccount: (input: UnhideHdAccountInput) => call("keyrings.unhideHdAccount", input),
    removePrivateKeyKeyring: (input: RemovePrivateKeyKeyringInput) => call("keyrings.removePrivateKeyKeyring", input),
    exportMnemonic: (input: ExportMnemonicInput) => call("keyrings.exportMnemonic", input),
    exportPrivateKey: (input: ExportPrivateKeyInput) => call("keyrings.exportPrivateKey", input),
  },
  transactions: {
    listHistory: (input?: WalletApiTransactionsInput) => call("transactions.listHistory", input),
    getDetail: (input: WalletApiTransactionDetailInput) => call("transactions.getDetail", input),
    requestSendTransactionApproval: (input: RequestSendTransactionApprovalInput) =>
      call("transactions.requestSendTransactionApproval", input),
    rerunPrepare: (input: RerunTransactionPrepareInput) => call("transactions.rerunPrepare", input),
    applyDraftEdit: (input: ApplyTransactionDraftEditInput) => call("transactions.applyDraftEdit", input),
  },
});
