export type { ApprovalDetail } from "../ui/protocol/models/approvals.js";
export type {
  CoreApplyTransactionDraftEditInput,
  CoreConfirmNewMnemonicInput,
  CoreCreateWalletFromMnemonicInput,
  CoreDeriveAccountInput,
  CoreExportMnemonicInput,
  CoreExportPrivateKeyInput,
  CoreGenerateMnemonicInput,
  CoreGetAccountsByKeyringInput,
  CoreHideHdAccountInput,
  CoreImportMnemonicInput,
  CoreImportPrivateKeyInput,
  CoreImportWalletFromMnemonicInput,
  CoreImportWalletFromPrivateKeyInput,
  CoreLogger,
  CoreMarkBackedUpInput,
  CoreProviderApi,
  CoreReadApi,
  CoreReadChangeListener,
  CoreRemovePrivateKeyKeyringInput,
  CoreRenameAccountInput,
  CoreRenameKeyringInput,
  CoreRequestSendTransactionApprovalInput,
  CoreRerunTransactionPrepareInput,
  CoreResolveApprovalInput,
  CoreRuntime,
  CoreRuntimeBootOptions,
  CoreRuntimeEnvironment,
  CoreSelectWalletChainInput,
  CoreSessionLockInput,
  CoreSessionSetAutoLockDurationInput,
  CoreSessionUnlockInput,
  CoreStorageInput,
  CoreSwitchActiveAccountInput,
  CoreUnhideHdAccountInput,
  CoreUnsubscribe,
  CoreWalletUiApi,
  CreateCoreRuntimeInput,
} from "./coreRuntime.js";
export { createArxWallet, createArxWalletRuntime } from "./createArxWallet.js";
export { createEip155WalletNamespaceModule } from "./modules/eip155.js";
export { createNamespaceManifestFromWalletNamespaceModule } from "./modules/manifestInterop.js";
export type {
  ArxWallet,
  ArxWalletStoragePorts,
  CreateArxWalletInput,
  DappConnectionProjection,
  DappConnectionRecord,
  DappConnectionsState,
  NamespaceEngineDefinition,
  NamespaceEngineFactories,
  NamespaceEngineFacts,
  WalletAccounts,
  WalletApprovalDetails,
  WalletApprovals,
  WalletAttention,
  WalletBackupStatus,
  WalletCreateUiOptions,
  WalletDappConnections,
  WalletNamespaceModule,
  WalletNamespaces,
  WalletNetworks,
  WalletPermissions,
  WalletProvider,
  WalletProviderConnectionProjection,
  WalletSession,
  WalletSetupState,
  WalletSnapshots,
  WalletUi,
  WalletUiDispatchInput,
} from "./types.js";
export { assertValidWalletNamespaceModule } from "./validation.js";
